### PR TITLE
update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by CFourPO**
* added a few missing steps and formatted a little

### CODE REVIEW

**Review by nickpalenchar — CHANGES_REQUESTED** [review]
@CFourPO you made an ordered list with all `1.`s??

(ill probably fix that myself if you don't get to it 🍞)

**Comment by nickpalenchar** [comment]
wait I think I didnt see is right ¯\_(ツ)_/¯

**Review by nickpalenchar — APPROVED** [review]

**Comment by CFourPO** [comment]
Aren't you supposed to be the markdown guru? It numbers it automatically, so you don't have to go back and change each of the numbers if you decide you want to add steps later \o/

**Comment by nickpalenchar** [comment]
Wow embarrassed to say I did **not** know that but it makes so much sense!!! I was once thinking when actually numbering how inconvenient it was to renumber if i inserted something.... lol

**Pull request merged**
